### ISSUE TITLE
support passing path as string

### ISSUE THREAD

**Issue by woylie** [woylie/flop_phoenix#111]
Currently, the path helper needs to be passed as an mfa tuple to the `table`, `pagination` and `cursor_pagination` components.

```elixir
<.pagination meta={@meta} path_helper={{Routes, :some_path, [@socket, :index]}} />
```

Phoenix 1.7 will come with verified routes, allowing you to use the `~p` sigil, which compiles down to a string. `flop_phoenix` should allow to _either_ reference a path helper as before, _or_ to pass a path as a string directly.

```elixir
<.pagination meta={@meta} path={~p"/some/path"} />
```

The Flop query parameters should be merged into the query parameters of the given path.

## Tasks

- [x] `build_path/3`: handle string as first argument
- [x] `validate_path_helper_or_event!/2`: update validation to accept string
- [x] ensure all components accept a string as `path`
